<?php
if (! defined('ABSPATH')) exit;

return array(

    // ─── CITRUS WHISPER ─────────────────────────────────────────
    'citrus-whisper' => array(
        'id' => 'citruswhisper',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Citrus Whisper',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Citrus Whisper',
        'tagline'       => 'A sun-drenched grove, softly exhaled.',
        'desc'          => 'Bright Italian lemon and sun-warmed mandarin, drying down to clean white musk.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.8',
        'reviews'       => '156',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── PEACH GLOW ─────────────────────────────────────────────
    'peach-glow' => array(
        'id' => 'peachglow',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Peach Glow',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Peach Glow',
        'tagline'       => 'Velvet skin, golden afternoon.',
        'desc'          => 'Lush, ripe peach at its sweetest moment with soft amber base.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.8',
        'reviews'       => '142',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── ROSE MIRAGE ────────────────────────────────────────────
    'rose-mirage' => array(
        'id' => 'rosemirage',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Rose Mirage',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Rose Mirage',
        'tagline'       => 'The idea of a rose, not its weight.',
        'desc'          => 'Sheer, dewy rose with peony freshness and cashmere softness.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.9',
        'reviews'       => '178',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── LIME VEIL ──────────────────────────────────────────────
    'lime-veil' => array(
        'id' => 'limeveil',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Lime Veil',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Lime Veil',
        'tagline'       => 'Crisp green air, freshly cut.',
        'desc'          => 'Persian lime zest meets green leaf and a whisper of sea salt.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.7',
        'reviews'       => '134',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── MORNING TEA ────────────────────────────────────────────
    'morning-tea' => array(
        'id' => 'morningtea',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Morning Tea',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Morning Tea',
        'tagline'       => 'Quiet warmth in a quiet room.',
        'desc'          => 'Bergamot-touched Earl Grey above soft warm wood.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.8',
        'reviews'       => '167',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── LILY DEW ───────────────────────────────────────────────
    'lily-dew' => array(
        'id' => 'lilydew',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Lily Dew',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Lily Dew',
        'tagline'       => 'Petals before the sun arrives.',
        'desc'          => 'White lily petals holding morning dew with iris softness.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.7',
        'reviews'       => '121',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── GRAPEFRUIT MUSE ────────────────────────────────────────
    'grapefruit-muse' => array(
        'id' => 'grapefrruitmuse',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Grapefruit Muse',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Grapefruit Muse',
        'tagline'       => 'Bold, bright, unapologetically alive.',
        'desc'          => 'Pink grapefruit with yuzu twist and white cedar depth.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.8',
        'reviews'       => '189',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── SWEET PETAL ────────────────────────────────────────────
    'sweet-petal' => array(
        'id' => 'sweetpetal',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Sweet Petal',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Sweet Petal',
        'tagline'       => 'Softness, distilled.',
        'desc'          => 'Cherry blossom meets magnolia in transparent floral with sheer musk.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.9',
        'reviews'       => '203',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── BERGAMOT BREEZE ────────────────────────────────────────
    'bergamot-breeze' => array(
        'id' => 'bergamotbreeze',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Bergamot Breeze',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Bergamot Breeze',
        'tagline'       => 'The freshest thing you\'ll smell today.',
        'desc'          => 'Classic bergamot with neroli sparkle and ocean mist transparency.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.9',
        'reviews'       => '215',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── FREESIA MIST ───────────────────────────────────────────
    'freesia-mist' => array(
        'id' => 'freesiamist',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Freesia Mist',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Freesia Mist',
        'tagline'       => 'A spring field, remembered.',
        'desc'          => 'Fresh-cut freesia with violet leaf and soft powder anchor.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.7',
        'reviews'       => '98',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── BERRY KISS ─────────────────────────────────────────────
    'berry-kiss' => array(
        'id' => 'berrykiss',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Berry Kiss',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Berry Kiss',
        'tagline'       => 'Rich, lush, unexpectedly refined.',
        'desc'          => 'Ripe blackberry and tart raspberry leaf with dark musk base.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.8',
        'reviews'       => '145',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── CANDY CLOUD ────────────────────────────────────────────
    'candy-cloud' => array(
        'id' => 'candycloud',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Candy Cloud',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Candy Cloud',
        'tagline'       => 'Pure joy, absolutely weightless.',
        'desc'          => 'Spun sugar, raspberry, and cotton candy. Bright and joyful.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.9',
        'reviews'       => '231',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── LAVENDER BLISS ─────────────────────────────────────────
    'lavender-bliss' => array(
        'id' => 'lavenderbliss',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Lavender Bliss',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Lavender Bliss',
        'tagline'       => 'Stillness you can wear.',
        'desc'          => 'Provence lavender with chamomile softness and warm vetiver root.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.8',
        'reviews'       => '176',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── SUNNY DAISY ────────────────────────────────────────────
    'sunny-daisy' => array(
        'id' => 'sunnydaisy',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Sunny Daisy',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Sunny Daisy',
        'tagline'       => 'Happiness has a scent.',
        'desc'          => 'Cheerful daisy petals with lemon grass brightness and fresh cotton.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.8',
        'reviews'       => '162',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── BUBBLE GUM ─────────────────────────────────────────────
    'bubble-gum' => array(
        'id' => 'bubblegum',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Bubble Gum',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Bubble Gum',
        'tagline'       => 'Blissfully, unapologetically sweet.',
        'desc'          => 'Classic bubble gum with strawberry and soft vanilla.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.9',
        'reviews'       => '248',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── BABY POWDER ────────────────────────────────────────────
    'baby-powder' => array(
        'id' => 'babypowder',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Baby Powder',
        'subtitle'      => 'Deodorizing &amp; Conditioning Spray &middot; Baby Powder',
        'tagline'       => 'Soft as a first breath.',
        'desc'          => 'Clean talc, soft iris, and spotless cotton. Pure comfort.',
        'price'         => '24.00',
        'currency'      => '$',
        'size'          => '250 ml',
        'badge'         => 'Cologne &middot; Leave-On',
        'type'          => 'Deodorizing Spray',
        'rating'        => '4.9',
        'reviews'       => '267',
        'bottle_badge'  => 'IFRA',
        'bottle_ings'   => array(
            array('Odor Neutralizer', '2.0%'),
            array('Oat Protein', '0.5%'),
            array('Panthenol', '0.3%'),
            array('Aloe Vera', '0.2%'),
        ),
        'stats' => array(
            array('250 ml', 'Size'),
            array('pH 5.0&ndash;5.8', 'Target pH'),
            array('0%', 'Parabens'),
            array('IFRA', 'Fragrance'),
        ),
        'benefits_title' => 'Triple-action formula, salon-grade finish.',
        'benefits' => array(
            array('&#x2728;', 'Triple Odor Neutralization', 'Cyclodextrin, zinc ricinoleate, and enzymatic deodorizer work through three distinct mechanisms.'),
            array('&#x1F33E;', 'Oat Protein Conditioning', 'Hydrolyzed oat protein smooths the cuticle and adds natural shine.'),
            array('&#x1F4A7;', 'Leave-On, No Rinse', 'Spray and go. No bath required. Dries clear, no residue.'),
            array('&#x1F6E1;', 'IFRA &amp; ECOCERT Aligned', 'Fragrance meets IFRA safety standards. Preservative system is ECOCERT-aligned.'),
        ),
        'ingredients' => array(
            array('&#x1F4A7;', 'Cyclodextrin Complex', '2.0%', 'Molecular cage traps odor compounds.', true, 'HERO'),
            array('&#x1F33F;', 'Zinc Ricinoleate', '0.8%', 'Zinc-based neutralizer from castor oil.', true, 'HERO'),
            array('&#x1F9EC;', 'Enzymatic Deodorizer', '0.5%', 'Breaks down odor at the molecular level.', true, 'HERO'),
            array('&#x1F33E;', 'Hydrolyzed Oat Protein', '0.5%', 'Coat conditioning and shine.', false, ''),
            array('&#x1F33C;', 'Panthenol (B5)', '0.3%', 'Moisture retention and elasticity.', false, ''),
            array('&#x1F33F;', 'Aloe Barbadensis', '0.2%', 'Soothes skin on contact.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Shake 5&ndash;6 times before each use.'),
            array('02', 'Spray evenly', 'Hold 15&ndash;20 cm from coat. Spray across back, sides, and neck.'),
            array('03', 'Massage in', 'Work through fur with hands for even distribution.'),
            array('04', 'Let dry', 'Air dry naturally. No rinsing needed.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For best results, spray on a freshly brushed coat. Brushing first removes loose fur and lets the spray reach the skin.'),
        'dogs' => array(
            'Dogs needing a quick freshening between baths',
            'Active dogs after walks or outdoor play',
            'Show dogs before events',
            'Dogs with mild coat odor',
            'Multi-dog households',
            'Any breed or coat type',
        ),
        'dog_cta_title' => 'Freshen up without a full bath.',
        'dog_cta_desc'  => 'A quick spray refreshes the coat, neutralizes odor, and leaves a lasting, salon-quality scent.',
        'dog_cta_tags'  => array('Leave-On', 'No Rinse', 'IFRA-Compliant', 'All Breeds'),
        'reviews_title'  => 'Pet parents love this scent.',
        'review_list' => array(
            array('Jessica M.', 'Golden Retriever', 'The scent lasts all day and my dog\'s coat feels so soft afterwards.'),
            array('Carlos R.', 'French Bulldog', 'Finally a spray that actually neutralizes odor instead of just covering it up.'),
            array('Dr. Amy L.', 'Veterinarian', 'Well-formulated. The oat protein is a smart addition for coat health.'),
        ),
        'cta_title' => 'Salon-quality freshness.',
        'cta_sub'   => 'In one quick spray.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'IFRA-Compliant',
            'No Parabens',
        ),
    ),

    // ─── CLEAN ESSENTIALS ───────────────────────────────────────
    'clean-essentials' => array(
        'id' => 'cleanessentials',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-back.png',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Clean Essentials&trade;',
        'subtitle'      => 'Daily Oral Care Spray &middot; Original Formula',
        'tagline'       => 'Fresh breath starts with clean science.',
        'desc'          => 'Zinc gluconate and sodium hexametaphosphate neutralize bad breath and help control tartar. No alcohol, no xylitol.',
        'price'         => '12.99',
        'currency'      => '$',
        'size'          => '60 mL',
        'badge'         => 'Original Formula',
        'type'          => 'Oral Care Spray',
        'rating'        => '4.7',
        'reviews'       => '89',
        'bottle_badge'  => 'Daily Care',
        'bottle_ings'   => array(
            array('Active System', 'varies'),
            array('Zinc Gluconate', '0.4%'),
            array('Aloe Vera', '0.2%'),
            array('Glycerin', '3.0%'),
        ),
        'stats' => array(
            array('60 mL', 'Size'),
            array('0%', 'Alcohol'),
            array('0%', 'Xylitol'),
            array('Daily', 'Use'),
        ),
        'benefits_title' => 'Professional-grade oral care.',
        'benefits' => array(
            array('&#x1F9F7;', 'Targets Bad Breath at Source', 'Neutralizes volatile sulfur compounds, not just masks them.'),
            array('&#x1F6E1;', 'Fights Tartar Buildup', 'Active ingredients help prevent plaque from mineralizing into tartar.'),
            array('&#x1F4A7;', 'No Alcohol, No Xylitol', 'Safe formula without ingredients that cause irritation or toxicity risk.'),
            array('&#x2705;', 'Vet-Friendly Formula', 'Developed with veterinary input. Safe for daily use.'),
        ),
        'ingredients' => array(
            array('&#x1F9F7;', 'Active System', 'varies', 'Primary mechanism for oral care.', true, 'HERO'),
            array('&#x1F4A7;', 'Zinc Gluconate', '0.4%', 'Neutralizes sulfur compounds causing bad breath.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '0.2%', 'Soothes gum tissue.', true, 'HERO'),
            array('&#x1F4A7;', 'Glycerin', '3.0%', 'Humectant base.', false, ''),
            array('&#x1F6E1;', 'SHMP', '0.3%', 'Sodium hexametaphosphate. Tartar control.', false, ''),
            array('&#x1F33F;', 'Preservative System', '0.8%', 'Paraben-free. Effective at low levels.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake gently', 'Shake before each use.'),
            array('02', 'Apply 2&ndash;3 sprays', 'Spray directly into mouth, targeting teeth and gum line.'),
            array('03', 'No rinsing', 'Let the formula work. No food or water for 30 minutes.'),
            array('04', 'Use daily', 'Once or twice daily for best results.'),
        ),
        'pro_tip' => array('&#x1F9F7;', 'For dogs that resist mouth sprays, try spraying onto a finger and rubbing along the gum line.'),
        'dogs' => array(
            'Dogs with bad breath',
            'Dogs prone to tartar buildup',
            'Senior dogs with dental issues',
            'Dogs who resist tooth brushing',
            'Post-dental cleaning maintenance',
            'All breeds',
        ),
        'dog_cta_title' => 'Better breath starts today.',
        'dog_cta_desc'  => 'No brushing required. Just spray, let it work, and enjoy fresher breath.',
        'dog_cta_tags'  => array('No Xylitol', 'No Alcohol', 'Vet-Friendly', 'Daily Use'),
        'reviews_title'  => 'Fresher breath, happier owners.',
        'review_list' => array(
            array('Sarah K.', 'Labrador', 'The difference after one week is remarkable. His breath is so much better.'),
            array('Mike T.', 'Senior Poodle', 'My 12-year-old won\'t let me brush his teeth. This spray is a lifesaver.'),
            array('Dr. Chen', 'Veterinarian', 'I recommend this to clients as part of their dog\'s daily oral care routine.'),
        ),
        'cta_title' => 'Professional-grade oral care.',
        'cta_sub'   => 'No brushing required.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'No Xylitol',
            'Vet-Friendly',
        ),
    ),

    // ─── ENZYME DEFENSE ─────────────────────────────────────────
    'enzyme-defense' => array(
        'id' => 'enzymedefense',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-back.png',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Enzyme Defense&trade;',
        'subtitle'      => 'Daily Oral Care Spray &middot; Enzyme System',
        'tagline'       => 'Biofilm doesn\'t stand a chance.',
        'desc'          => 'Glucose oxidase, lactoferrin, and lysozyme — an enzyme trio that breaks down biofilm.',
        'price'         => '16.99',
        'currency'      => '$',
        'size'          => '60 mL',
        'badge'         => 'Enzyme System',
        'type'          => 'Oral Care Spray',
        'rating'        => '4.8',
        'reviews'       => '67',
        'bottle_badge'  => 'Enzyme',
        'bottle_ings'   => array(
            array('Active System', 'varies'),
            array('Zinc Gluconate', '0.4%'),
            array('Aloe Vera', '0.2%'),
            array('Glycerin', '3.0%'),
        ),
        'stats' => array(
            array('60 mL', 'Size'),
            array('3', 'Enzymes'),
            array('0%', 'Alcohol'),
            array('Daily', 'Use'),
        ),
        'benefits_title' => 'Professional-grade oral care.',
        'benefits' => array(
            array('&#x1F9F7;', 'Targets Bad Breath at Source', 'Neutralizes volatile sulfur compounds, not just masks them.'),
            array('&#x1F6E1;', 'Fights Tartar Buildup', 'Active ingredients help prevent plaque from mineralizing into tartar.'),
            array('&#x1F4A7;', 'No Alcohol, No Xylitol', 'Safe formula without ingredients that cause irritation or toxicity risk.'),
            array('&#x2705;', 'Vet-Friendly Formula', 'Developed with veterinary input. Safe for daily use.'),
        ),
        'ingredients' => array(
            array('&#x1F9F7;', 'Active System', 'varies', 'Primary mechanism for oral care.', true, 'HERO'),
            array('&#x1F4A7;', 'Zinc Gluconate', '0.4%', 'Neutralizes sulfur compounds causing bad breath.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '0.2%', 'Soothes gum tissue.', true, 'HERO'),
            array('&#x1F4A7;', 'Glycerin', '3.0%', 'Humectant base.', false, ''),
            array('&#x1F6E1;', 'SHMP', '0.3%', 'Sodium hexametaphosphate. Tartar control.', false, ''),
            array('&#x1F33F;', 'Preservative System', '0.8%', 'Paraben-free. Effective at low levels.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake gently', 'Shake before each use.'),
            array('02', 'Apply 2&ndash;3 sprays', 'Spray directly into mouth, targeting teeth and gum line.'),
            array('03', 'No rinsing', 'Let the formula work. No food or water for 30 minutes.'),
            array('04', 'Use daily', 'Once or twice daily for best results.'),
        ),
        'pro_tip' => array('&#x1F9F7;', 'For dogs that resist mouth sprays, try spraying onto a finger and rubbing along the gum line.'),
        'dogs' => array(
            'Dogs with bad breath',
            'Dogs prone to tartar buildup',
            'Senior dogs with dental issues',
            'Dogs who resist tooth brushing',
            'Post-dental cleaning maintenance',
            'All breeds',
        ),
        'dog_cta_title' => 'Better breath starts today.',
        'dog_cta_desc'  => 'No brushing required. Just spray, let it work, and enjoy fresher breath.',
        'dog_cta_tags'  => array('No Xylitol', 'No Alcohol', 'Vet-Friendly', 'Daily Use'),
        'reviews_title'  => 'Fresher breath, happier owners.',
        'review_list' => array(
            array('Sarah K.', 'Labrador', 'The difference after one week is remarkable. His breath is so much better.'),
            array('Mike T.', 'Senior Poodle', 'My 12-year-old won\'t let me brush his teeth. This spray is a lifesaver.'),
            array('Dr. Chen', 'Veterinarian', 'I recommend this to clients as part of their dog\'s daily oral care routine.'),
        ),
        'cta_title' => 'Professional-grade oral care.',
        'cta_sub'   => 'No brushing required.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'No Xylitol',
            'Vet-Friendly',
        ),
    ),

    // ─── PRO DEFENSE ────────────────────────────────────────────
    'pro-defense' => array(
        'id' => 'prodefense',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-back.png',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Pro Defense&trade;',
        'subtitle'      => 'Daily Oral Care Spray &middot; 4-Action System',
        'tagline'       => 'Four mechanisms. One spray. Zero compromise.',
        'desc'          => 'CPC, zinc PCA, and sodium hexametaphosphate — four mechanisms in one formula.',
        'price'         => '15.99',
        'currency'      => '$',
        'size'          => '60 mL',
        'badge'         => '4-Action',
        'type'          => 'Oral Care Spray',
        'rating'        => '4.9',
        'reviews'       => '142',
        'bottle_badge'  => 'Pro',
        'bottle_ings'   => array(
            array('Active System', 'varies'),
            array('Zinc Gluconate', '0.4%'),
            array('Aloe Vera', '0.2%'),
            array('Glycerin', '3.0%'),
        ),
        'stats' => array(
            array('60 mL', 'Size'),
            array('4', 'Actions'),
            array('CPC', 'Active'),
            array('Daily', 'Use'),
        ),
        'benefits_title' => 'Professional-grade oral care.',
        'benefits' => array(
            array('&#x1F9F7;', 'Targets Bad Breath at Source', 'Neutralizes volatile sulfur compounds, not just masks them.'),
            array('&#x1F6E1;', 'Fights Tartar Buildup', 'Active ingredients help prevent plaque from mineralizing into tartar.'),
            array('&#x1F4A7;', 'No Alcohol, No Xylitol', 'Safe formula without ingredients that cause irritation or toxicity risk.'),
            array('&#x2705;', 'Vet-Friendly Formula', 'Developed with veterinary input. Safe for daily use.'),
        ),
        'ingredients' => array(
            array('&#x1F9F7;', 'Active System', 'varies', 'Primary mechanism for oral care.', true, 'HERO'),
            array('&#x1F4A7;', 'Zinc Gluconate', '0.4%', 'Neutralizes sulfur compounds causing bad breath.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '0.2%', 'Soothes gum tissue.', true, 'HERO'),
            array('&#x1F4A7;', 'Glycerin', '3.0%', 'Humectant base.', false, ''),
            array('&#x1F6E1;', 'SHMP', '0.3%', 'Sodium hexametaphosphate. Tartar control.', false, ''),
            array('&#x1F33F;', 'Preservative System', '0.8%', 'Paraben-free. Effective at low levels.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake gently', 'Shake before each use.'),
            array('02', 'Apply 2&ndash;3 sprays', 'Spray directly into mouth, targeting teeth and gum line.'),
            array('03', 'No rinsing', 'Let the formula work. No food or water for 30 minutes.'),
            array('04', 'Use daily', 'Once or twice daily for best results.'),
        ),
        'pro_tip' => array('&#x1F9F7;', 'For dogs that resist mouth sprays, try spraying onto a finger and rubbing along the gum line.'),
        'dogs' => array(
            'Dogs with bad breath',
            'Dogs prone to tartar buildup',
            'Senior dogs with dental issues',
            'Dogs who resist tooth brushing',
            'Post-dental cleaning maintenance',
            'All breeds',
        ),
        'dog_cta_title' => 'Better breath starts today.',
        'dog_cta_desc'  => 'No brushing required. Just spray, let it work, and enjoy fresher breath.',
        'dog_cta_tags'  => array('No Xylitol', 'No Alcohol', 'Vet-Friendly', 'Daily Use'),
        'reviews_title'  => 'Fresher breath, happier owners.',
        'review_list' => array(
            array('Sarah K.', 'Labrador', 'The difference after one week is remarkable. His breath is so much better.'),
            array('Mike T.', 'Senior Poodle', 'My 12-year-old won\'t let me brush his teeth. This spray is a lifesaver.'),
            array('Dr. Chen', 'Veterinarian', 'I recommend this to clients as part of their dog\'s daily oral care routine.'),
        ),
        'cta_title' => 'Professional-grade oral care.',
        'cta_sub'   => 'No brushing required.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'No Xylitol',
            'Vet-Friendly',
        ),
    ),

    // ─── NATURE SHIELD ──────────────────────────────────────────
    'nature-shield' => array(
        'id' => 'natureshield',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-back.png',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Nature Shield&trade;',
        'subtitle'      => 'Daily Oral Care Spray &middot; All-Natural',
        'tagline'       => 'Nature-powered. Science-proven.',
        'desc'          => 'Nisin, green tea extract, and pomegranate — nature\'s own antimicrobial arsenal.',
        'price'         => '17.99',
        'currency'      => '$',
        'size'          => '60 mL',
        'badge'         => 'All-Natural',
        'type'          => 'Oral Care Spray',
        'rating'        => '4.9',
        'reviews'       => '203',
        'bottle_badge'  => 'Natural',
        'bottle_ings'   => array(
            array('Active System', 'varies'),
            array('Zinc Gluconate', '0.4%'),
            array('Aloe Vera', '0.2%'),
            array('Glycerin', '3.0%'),
        ),
        'stats' => array(
            array('60 mL', 'Size'),
            array('Nisin', 'Active'),
            array('100%', 'Natural'),
            array('Daily', 'Use'),
        ),
        'benefits_title' => 'Professional-grade oral care.',
        'benefits' => array(
            array('&#x1F9F7;', 'Targets Bad Breath at Source', 'Neutralizes volatile sulfur compounds, not just masks them.'),
            array('&#x1F6E1;', 'Fights Tartar Buildup', 'Active ingredients help prevent plaque from mineralizing into tartar.'),
            array('&#x1F4A7;', 'No Alcohol, No Xylitol', 'Safe formula without ingredients that cause irritation or toxicity risk.'),
            array('&#x2705;', 'Vet-Friendly Formula', 'Developed with veterinary input. Safe for daily use.'),
        ),
        'ingredients' => array(
            array('&#x1F9F7;', 'Active System', 'varies', 'Primary mechanism for oral care.', true, 'HERO'),
            array('&#x1F4A7;', 'Zinc Gluconate', '0.4%', 'Neutralizes sulfur compounds causing bad breath.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '0.2%', 'Soothes gum tissue.', true, 'HERO'),
            array('&#x1F4A7;', 'Glycerin', '3.0%', 'Humectant base.', false, ''),
            array('&#x1F6E1;', 'SHMP', '0.3%', 'Sodium hexametaphosphate. Tartar control.', false, ''),
            array('&#x1F33F;', 'Preservative System', '0.8%', 'Paraben-free. Effective at low levels.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake gently', 'Shake before each use.'),
            array('02', 'Apply 2&ndash;3 sprays', 'Spray directly into mouth, targeting teeth and gum line.'),
            array('03', 'No rinsing', 'Let the formula work. No food or water for 30 minutes.'),
            array('04', 'Use daily', 'Once or twice daily for best results.'),
        ),
        'pro_tip' => array('&#x1F9F7;', 'For dogs that resist mouth sprays, try spraying onto a finger and rubbing along the gum line.'),
        'dogs' => array(
            'Dogs with bad breath',
            'Dogs prone to tartar buildup',
            'Senior dogs with dental issues',
            'Dogs who resist tooth brushing',
            'Post-dental cleaning maintenance',
            'All breeds',
        ),
        'dog_cta_title' => 'Better breath starts today.',
        'dog_cta_desc'  => 'No brushing required. Just spray, let it work, and enjoy fresher breath.',
        'dog_cta_tags'  => array('No Xylitol', 'No Alcohol', 'Vet-Friendly', 'Daily Use'),
        'reviews_title'  => 'Fresher breath, happier owners.',
        'review_list' => array(
            array('Sarah K.', 'Labrador', 'The difference after one week is remarkable. His breath is so much better.'),
            array('Mike T.', 'Senior Poodle', 'My 12-year-old won\'t let me brush his teeth. This spray is a lifesaver.'),
            array('Dr. Chen', 'Veterinarian', 'I recommend this to clients as part of their dog\'s daily oral care routine.'),
        ),
        'cta_title' => 'Professional-grade oral care.',
        'cta_sub'   => 'No brushing required.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'No Xylitol',
            'Vet-Friendly',
        ),
    ),

    // ─── FRESH GUARD ────────────────────────────────────────────
    'fresh-guard' => array(
        'id' => 'freshguard',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-back.png',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Fresh Guard&trade;',
        'subtitle'      => 'Dog Oral Care Water Additive &middot; 16 fl oz',
        'tagline'       => 'Fresher breath. Just add to water.',
        'desc'          => 'Add to your dog\'s water bowl daily for continuous oral care. Zinc gluconate and chlorophyllin.',
        'price'         => '24.99',
        'currency'      => '$',
        'size'          => '473 mL (16 fl oz)',
        'badge'         => 'For Dogs',
        'type'          => 'Water Additive',
        'rating'        => '4.8',
        'reviews'       => '237',
        'bottle_badge'  => 'Dog',
        'bottle_ings'   => array(
            array('Active System', 'varies'),
            array('Zinc Gluconate', '0.4%'),
            array('Aloe Vera', '0.2%'),
            array('Glycerin', '3.0%'),
        ),
        'stats' => array(
            array('473 mL', 'Size'),
            array('~30 days', 'Supply'),
            array('0%', 'Alcohol'),
            array('Daily', 'Use'),
        ),
        'benefits_title' => 'Professional-grade oral care.',
        'benefits' => array(
            array('&#x1F9F7;', 'Targets Bad Breath at Source', 'Neutralizes volatile sulfur compounds, not just masks them.'),
            array('&#x1F6E1;', 'Fights Tartar Buildup', 'Active ingredients help prevent plaque from mineralizing into tartar.'),
            array('&#x1F4A7;', 'No Alcohol, No Xylitol', 'Safe formula without ingredients that cause irritation or toxicity risk.'),
            array('&#x2705;', 'Vet-Friendly Formula', 'Developed with veterinary input. Safe for daily use.'),
        ),
        'ingredients' => array(
            array('&#x1F9F7;', 'Active System', 'varies', 'Primary mechanism for oral care.', true, 'HERO'),
            array('&#x1F4A7;', 'Zinc Gluconate', '0.4%', 'Neutralizes sulfur compounds causing bad breath.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '0.2%', 'Soothes gum tissue.', true, 'HERO'),
            array('&#x1F4A7;', 'Glycerin', '3.0%', 'Humectant base.', false, ''),
            array('&#x1F6E1;', 'SHMP', '0.3%', 'Sodium hexametaphosphate. Tartar control.', false, ''),
            array('&#x1F33F;', 'Preservative System', '0.8%', 'Paraben-free. Effective at low levels.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake gently', 'Shake before each use.'),
            array('02', 'Apply 2&ndash;3 sprays', 'Spray directly into mouth, targeting teeth and gum line.'),
            array('03', 'No rinsing', 'Let the formula work. No food or water for 30 minutes.'),
            array('04', 'Use daily', 'Once or twice daily for best results.'),
        ),
        'pro_tip' => array('&#x1F9F7;', 'For dogs that resist mouth sprays, try spraying onto a finger and rubbing along the gum line.'),
        'dogs' => array(
            'Dogs with bad breath',
            'Dogs prone to tartar buildup',
            'Senior dogs with dental issues',
            'Dogs who resist tooth brushing',
            'Post-dental cleaning maintenance',
            'All breeds',
        ),
        'dog_cta_title' => 'Better breath starts today.',
        'dog_cta_desc'  => 'No brushing required. Just spray, let it work, and enjoy fresher breath.',
        'dog_cta_tags'  => array('No Xylitol', 'No Alcohol', 'Vet-Friendly', 'Daily Use'),
        'reviews_title'  => 'Fresher breath, happier owners.',
        'review_list' => array(
            array('Sarah K.', 'Labrador', 'The difference after one week is remarkable. His breath is so much better.'),
            array('Mike T.', 'Senior Poodle', 'My 12-year-old won\'t let me brush his teeth. This spray is a lifesaver.'),
            array('Dr. Chen', 'Veterinarian', 'I recommend this to clients as part of their dog\'s daily oral care routine.'),
        ),
        'cta_title' => 'Professional-grade oral care.',
        'cta_sub'   => 'No brushing required.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'No Xylitol',
            'Vet-Friendly',
        ),
    ),

    // ─── GENTLE GUARD ───────────────────────────────────────────
    'gentle-guard' => array(
        'id' => 'gentleguard',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-back.png',
        'image' => '/wp-content/themes/boundless-native-theme/assets/img/products/cologne-bottle-front.png',
        'name'          => 'Gentle Guard&trade;',
        'subtitle'      => 'Cat Oral Care Water Additive &middot; 16 fl oz',
        'tagline'       => 'Gentle on felines. Relentless on plaque.',
        'desc'          => 'Cat-safe formula with taurine-safe enzyme blend. Add to water bowl daily.',
        'price'         => '24.99',
        'currency'      => '$',
        'size'          => '473 mL (16 fl oz)',
        'badge'         => 'For Cats',
        'type'          => 'Water Additive',
        'rating'        => '4.7',
        'reviews'       => '189',
        'bottle_badge'  => 'Cat',
        'bottle_ings'   => array(
            array('Active System', 'varies'),
            array('Zinc Gluconate', '0.4%'),
            array('Aloe Vera', '0.2%'),
            array('Glycerin', '3.0%'),
        ),
        'stats' => array(
            array('473 mL', 'Size'),
            array('~30 days', 'Supply'),
            array('Cat-Safe', 'pH'),
            array('Daily', 'Use'),
        ),
        'benefits_title' => 'Professional-grade oral care.',
        'benefits' => array(
            array('&#x1F9F7;', 'Targets Bad Breath at Source', 'Neutralizes volatile sulfur compounds, not just masks them.'),
            array('&#x1F6E1;', 'Fights Tartar Buildup', 'Active ingredients help prevent plaque from mineralizing into tartar.'),
            array('&#x1F4A7;', 'No Alcohol, No Xylitol', 'Safe formula without ingredients that cause irritation or toxicity risk.'),
            array('&#x2705;', 'Vet-Friendly Formula', 'Developed with veterinary input. Safe for daily use.'),
        ),
        'ingredients' => array(
            array('&#x1F9F7;', 'Active System', 'varies', 'Primary mechanism for oral care.', true, 'HERO'),
            array('&#x1F4A7;', 'Zinc Gluconate', '0.4%', 'Neutralizes sulfur compounds causing bad breath.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '0.2%', 'Soothes gum tissue.', true, 'HERO'),
            array('&#x1F4A7;', 'Glycerin', '3.0%', 'Humectant base.', false, ''),
            array('&#x1F6E1;', 'SHMP', '0.3%', 'Sodium hexametaphosphate. Tartar control.', false, ''),
            array('&#x1F33F;', 'Preservative System', '0.8%', 'Paraben-free. Effective at low levels.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake gently', 'Shake before each use.'),
            array('02', 'Apply 2&ndash;3 sprays', 'Spray directly into mouth, targeting teeth and gum line.'),
            array('03', 'No rinsing', 'Let the formula work. No food or water for 30 minutes.'),
            array('04', 'Use daily', 'Once or twice daily for best results.'),
        ),
        'pro_tip' => array('&#x1F9F7;', 'For dogs that resist mouth sprays, try spraying onto a finger and rubbing along the gum line.'),
        'dogs' => array(
            'Dogs with bad breath',
            'Dogs prone to tartar buildup',
            'Senior dogs with dental issues',
            'Dogs who resist tooth brushing',
            'Post-dental cleaning maintenance',
            'All breeds',
        ),
        'dog_cta_title' => 'Better breath starts today.',
        'dog_cta_desc'  => 'No brushing required. Just spray, let it work, and enjoy fresher breath.',
        'dog_cta_tags'  => array('No Xylitol', 'No Alcohol', 'Vet-Friendly', 'Daily Use'),
        'reviews_title'  => 'Fresher breath, happier owners.',
        'review_list' => array(
            array('Sarah K.', 'Labrador', 'The difference after one week is remarkable. His breath is so much better.'),
            array('Mike T.', 'Senior Poodle', 'My 12-year-old won\'t let me brush his teeth. This spray is a lifesaver.'),
            array('Dr. Chen', 'Veterinarian', 'I recommend this to clients as part of their dog\'s daily oral care routine.'),
        ),
        'cta_title' => 'Professional-grade oral care.',
        'cta_sub'   => 'No brushing required.',
        'trust' => array(
            'Free shipping $50+',
            '30-day guarantee',
            'No Xylitol',
            'Vet-Friendly',
        ),
    ),

);
