<?php
if (! defined('ABSPATH')) exit;

return array(

    // ─── ORIGINAL ────────────────────────────────────────────────
    'original' => array(
        'id'            => 'original',
        'name'          => 'Original&trade;',
        'subtitle'      => 'No-Chew &amp; Boundary Deterrent Spray &middot; 250 ml',
        'tagline'       => 'Firm boundaries. Gentle formula. No compromise.',
        'desc'          => 'The alcohol-free dog deterrent spray that protects your home without worrying about your dog. Denatonium benzoate — the world\'s most bitter compound — pairs with a triple essential oil scent barrier and skin-safe actives.',
        'price'         => '12.99',
        'currency'      => '&pound;',
        'size'          => '250 ml',
        'badge'         => 'Alcohol-Free &middot; Skin-Safe Formula',
        'type'          => 'No-Chew Deterrent Spray',
        'rating'        => '4.8',
        'reviews'       => '92',
        'bottle_badge'  => 'SKIN SAFE',
        'bottle_ings'   => array(
            array('Denatonium Benzoate', '0.015%'),
            array('Citronella Oil', '0.30%'),
            array('Peppermint Oil', '0.30%'),
            array('Allantoin', '0.20%'),
        ),
        'stats' => array(
            array('0.015%', 'Denatonium Benzoate'),
            array('pH 5.5&ndash;6.0', 'Skin Balanced'),
            array('0%', 'Alcohol'),
            array('Triple', 'Scent Barrier'),
        ),
        'benefits_title' => 'Science-backed deterrence, naturally safe',
        'benefits' => array(
            array('&#x1F61D;', 'World\'s Most Bitter Compound', 'Denatonium benzoate at 0.015% &mdash; calibrated precisely so one lick is the last lick. Used by vets and trainers worldwide.'),
            array('&#x1F33F;', 'Triple Essential Oil Scent Barrier', 'Citronella, lemongrass and peppermint oils create a layered olfactory boundary dogs instinctively avoid.'),
            array('&#x1F4A7;', 'Alcohol-Free &mdash; Genuinely Skin-Safe', 'BOUNDLESS Original contains zero alcohol. Glycerin and allantoin ensure the formula is safe even if overspray contacts your dog.'),
            array('&#x1F331;', 'Eco-Certified &amp; pH Balanced', 'Eco-certified preservative blend, Disodium EDTA for enhanced stability, and pH of 5.5&ndash;6.0. No parabens, no sulphates.'),
        ),
        'ingredients' => array(
            array('&#x1F61D;', 'Denatonium Benzoate', '0.015%', 'The world\'s most bitter compound. One lick creates an immediate, powerful aversion.', true, 'HERO'),
            array('&#x1F34B;', 'Citronella + Lemongrass', '0.60%', 'Dual citrus essential oils provide the first two layers of the scent barrier.', true, 'HERO'),
            array('&#x1F331;', 'Peppermint + Menthol', '0.40%', 'Cooling mint completes the triple barrier and adds repellent synergy.', true, 'HERO'),
            array('&#x1F33F;', 'Allantoin', '0.20%', 'Skin-soothing active that calms irritation if overspray contacts your dog.', false, ''),
            array('&#x1F4A7;', 'Glycerin + Propylene Glycol', '5.00%', 'Humectant duo providing skin conditioning and formula stability.', false, ''),
            array('&#x1F34E;', 'Apple Fruit Extract', '1.00%', 'Botanical extract providing antioxidant activity and pleasant top-note.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake &amp; aim', 'Hold bottle 20 cm from the target surface. Shake gently before first use.'),
            array('02', 'Spray 2&ndash;3 times', 'Apply evenly across the surface. Works on wood, fabric, leather, carpet, plastic and metal.'),
            array('03', 'Allow 60 seconds', 'Let the surface dry. The scent barrier activates immediately. The bitterant bonds to the surface.'),
            array('04', 'Reapply weekly', 'Reapply every 1&ndash;2 weeks or after cleaning. Combine with positive reinforcement.'),
        ),
        'pro_tip' => array('&#x1F33F;', 'For persistent chewers, apply to a small test area first and observe your dog\'s reaction after 5 minutes.'),
        'dogs' => array(
            'Persistent chewers and destructive dogs',
            'Puppies learning household boundaries',
            'Dogs that target furniture cables or shoes',
            'All breeds and coat types',
            'Multi-dog households',
            'Rescue dogs needing boundary training',
        ),
        'dog_cta_title' => 'Not sure if it\'s right for your dog?',
        'dog_cta_desc'  => 'If your dog chews furniture, targets cables, or ignores boundaries &mdash; BOUNDLESS Original was built for them.',
        'dog_cta_tags'  => array('Alcohol-Free', 'pH-Balanced', 'All Breeds', 'Trainer Recommended'),
        'reviews_title'  => 'Dogs stopped. Owners relieved.',
        'review_list' => array(
            array('Sarah R.', 'Labrador Retriever', 'Finally a spray I don\'t worry about. Milo is a Lab &mdash; he gets into everything. BOUNDLESS works and I\'m not panicking when he licks the sofa leg.'),
            array('James M.', 'Multi-dog household', 'Three dogs, one product. All three avoid the kitchen counter now. The mint smell is actually pleasant for us humans too.'),
            array('Priya T.', 'Rescue Mixed Breed', 'My rescue was a compulsive cable chewer. Two weeks of BOUNDLESS Original and zero incidents. The best formulated I\'ve found.'),
        ),
        'cta_title' => 'Firm boundaries. Gentle formula.',
        'cta_sub'   => 'The alcohol-free deterrent spray your dog will never get past.',
        'trust' => array(
            'Free shipping &pound;35+',
            '30-day guarantee',
            'Alcohol-Free',
            'Skin-Safe Formula',
        ),
    ),

    // ─── NATURAL ─────────────────────────────────────────────────
    'natural' => array(
        'id'            => 'natural',
        'name'          => 'Natural&trade;',
        'subtitle'      => 'Essential Oil Blend Deterrent Spray &middot; 250 ml',
        'tagline'       => 'Nature-powered protection. Zero compromise.',
        'desc'          => 'A plant-powered deterrent spray using a concentrated essential oil blend. Citronella, lemongrass, and peppermint work together to create a scent barrier dogs instinctively avoid &mdash; without any synthetic bitterants.',
        'price'         => '14.99',
        'currency'      => '&pound;',
        'size'          => '250 ml',
        'badge'         => 'Plant-Based &middot; Eco-Friendly',
        'type'          => 'Essential Oil Deterrent Spray',
        'rating'        => '4.7',
        'reviews'       => '64',
        'bottle_badge'  => 'ECO-CERT',
        'bottle_ings'   => array(
            array('Citronella Oil', '0.50%'),
            array('Lemongrass Oil', '0.40%'),
            array('Peppermint Oil', '0.35%'),
            array('Eucalyptus Oil', '0.25%'),
        ),
        'stats' => array(
            array('4', 'Essential Oils'),
            array('pH 5.5&ndash;6.0', 'Skin Balanced'),
            array('0%', 'Synthetic Bitterant'),
            array('100%', 'Plant-Based'),
        ),
        'benefits_title' => 'Pure plant protection, no compromise',
        'benefits' => array(
            array('&#x1F33F;', 'Concentrated Essential Oil Blend', 'Four premium essential oils &mdash; citronella, lemongrass, peppermint, and eucalyptus &mdash; create a multi-layered scent barrier that dogs instinctively avoid.'),
            array('&#x1F343;', 'No Synthetic Bitterants', 'Unlike our Original formula, Natural relies entirely on scent deterrence. No denatonium benzoate, no synthetic compounds. Just plants.'),
            array('&#x1F331;', 'Eco-Certified Formulation', 'Every ingredient is sustainably sourced and eco-certified. The bottle is made from recycled plastic. The formula is fully biodegradable.'),
            array('&#x1F415;', 'Safe for Sensitive Environments', 'Ideal for homes with cats, birds, or other pets sensitive to synthetic compounds. The essential oil blend is calibrated to deter dogs without disturbing other animals.'),
        ),
        'ingredients' => array(
            array('&#x1F33F;', 'Citronella Oil', '0.50%', 'Steam-distilled Cymbopogon nardus. Primary scent deterrent providing the foundation of the olfactory barrier.', true, 'HERO'),
            array('&#x1F34B;', 'Lemongrass Oil', '0.40%', 'Cymbopogon flexuosus. Citrus-fresh scent layer that reinforces citronella and prevents scent habituation.', true, 'HERO'),
            array('&#x1F331;', 'Peppermint Oil', '0.35%', 'Mentha piperita. Cooling mint completes the triple scent barrier and adds repellent synergy.', true, 'HERO'),
            array('&#x1F332;', 'Eucalyptus Oil', '0.25%', 'Eucalyptus globulus. Fourth scent layer providing lasting aromatic persistence.', false, ''),
            array('&#x1F4A7;', 'Glycerin', '3.00%', 'Plant-derived humectant providing formula stability and skin conditioning.', false, ''),
            array('&#x1F6E1;&#xFE0F;', 'Eco-Certified Preservative', '0.80%', 'Phenoxyethanol-based preservation system. Paraben-free, MIT-free.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Shake well', 'Essential oils separate naturally. Shake the bottle 5&ndash;6 times before each use for optimal distribution.'),
            array('02', 'Spray 3&ndash;4 times', 'Apply evenly from 20 cm. Natural formula may require slightly more coverage than our Original for equivalent effect.'),
            array('03', 'Allow 2 minutes', 'Let the surface absorb the essential oil blend. The scent barrier intensifies as the carrier evaporates.'),
            array('04', 'Reapply every 5&ndash;7 days', 'Essential oil deterrence requires more frequent reapplication. Reapply after cleaning or heavy rain on outdoor surfaces.'),
        ),
        'pro_tip' => array('&#x1F343;', 'Essential oils work best at room temperature. If the bottle has been stored in cold conditions, warm it gently between your hands before spraying for optimal scent release.'),
        'dogs' => array(
            'Dogs sensitive to synthetic compounds',
            'Homes with multiple pet species',
            'Puppies in early training',
            'Indoor/outdoor boundary setting',
            'Eco-conscious pet owners',
            'Dogs that respond strongly to scent cues',
        ),
        'dog_cta_title' => 'Prefer a purely natural approach?',
        'dog_cta_desc'  => 'If you want effective deterrence without any synthetic compounds, the Natural formula gives you plant-powered protection you can feel good about.',
        'dog_cta_tags'  => array('Plant-Based', 'Eco-Certified', 'No Synthetics', 'Biodegradable'),
        'reviews_title'  => 'Nature works. Owners agree.',
        'review_list' => array(
            array('Emma L.', 'Cockapoo', 'Love that it\'s completely plant-based. My cockapoo stopped going near the garden border within a week. The lemongrass scent is actually lovely.'),
            array('Tom H.', 'Cat &amp; Dog household', 'We needed something safe for our cat too. The Natural formula solved our problem without any worry about synthetic compounds near our other pets.'),
            array('Dr. Claire W.', 'Vet, 8 years', 'I recommend the Natural formula to clients who prefer plant-based solutions. The essential oil concentrations are well-calibrated &mdash; effective without being overwhelming.'),
        ),
        'cta_title' => 'Plant-powered protection.',
        'cta_sub'   => 'Four essential oils. Zero synthetics. Nature\'s own deterrent.',
        'trust' => array(
            'Free shipping &pound;35+',
            '30-day guarantee',
            '100% Plant-Based',
            'Eco-Certified',
        ),
    ),

    // ─── 2-IN-1 HOT SPOT ────────────────────────────────────────
    '2-in-1' => array(
        'id'            => 'hotspot',
        'name'          => '2-in-1&trade; Hot Spot',
        'subtitle'      => 'Treat + Deter Dual Action Spray &middot; 250 ml',
        'tagline'       => 'Soothe and protect. One spray does both.',
        'desc'          => 'The only deterrent spray that also treats hot spots. Allantoin and aloe vera soothe irritated skin while the triple scent barrier and bitterant stop further chewing. Dual-action formula for dogs that chew at sore areas.',
        'price'         => '16.99',
        'currency'      => '&pound;',
        'size'          => '250 ml',
        'badge'         => 'Dual-Action &middot; Soothing',
        'type'          => 'Hot Spot Treatment + Deterrent',
        'rating'        => '4.6',
        'reviews'       => '38',
        'bottle_badge'  => 'DUAL ACTION',
        'bottle_ings'   => array(
            array('Denatonium Benzoate', '0.012%'),
            array('Allantoin', '0.50%'),
            array('Aloe Vera', '1.00%'),
            array('Citronella Oil', '0.25%'),
        ),
        'stats' => array(
            array('Dual', 'Action Formula'),
            array('1.00%', 'Aloe Vera'),
            array('0.50%', 'Allantoin'),
            array('pH 5.5&ndash;6.0', 'Skin Balanced'),
        ),
        'benefits_title' => 'Treat the cause. Deter the habit.',
        'benefits' => array(
            array('&#x1FA79;', 'Dual-Action Formula', 'The only product that treats hot spots AND deters further chewing in a single spray. Two problems, one solution.'),
            array('&#x1F33F;', 'Aloe Vera + Allantoin', '1% aloe vera soothes on contact while allantoin promotes skin cell turnover. Together they calm irritation and accelerate healing.'),
            array('&#x1F61D;', 'Calibrated Bitterant', 'Denatonium benzoate at 0.012% &mdash; slightly lower than Original to be gentler on irritated skin while still providing effective taste deterrence.'),
            array('&#x1F4A7;', 'Moisturising Base', 'Glycerin-enriched base prevents the formula from drying out already-compromised skin. Hydrates while it protects.'),
        ),
        'ingredients' => array(
            array('&#x1FA79;', 'Allantoin', '0.50%', 'Promotes skin cell turnover and calms inflammation. The primary soothing active for hot spot treatment.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '1.00%', 'Aloe barbadensis leaf juice. Immediate cooling and soothing on contact. Hydrates damaged skin.', true, 'HERO'),
            array('&#x1F61D;', 'Denatonium Benzoate', '0.012%', 'Calibrated lower than Original for gentler application on irritated skin while maintaining deterrent efficacy.', true, 'HERO'),
            array('&#x1F34B;', 'Citronella Oil', '0.25%', 'Scent deterrent layer to reinforce the bitterant and create dual-mechanism aversion.', false, ''),
            array('&#x1F4A7;', 'Glycerin', '4.00%', 'Plant-derived humectant. Extra concentration provides additional moisturising for dry, irritated hot spot areas.', false, ''),
            array('&#x1F6E1;&#xFE0F;', 'Chamomile Extract', '0.15%', 'Matricaria recutita. Anti-inflammatory botanical that complements the allantoin soothing pathway.', false, ''),
        ),
        'inci' => '',
        'steps' => array(
            array('01', 'Clean the area', 'Gently clean the hot spot area with warm water. Pat dry. Do not apply to open wounds or broken skin.'),
            array('02', 'Spray from 15 cm', 'Hold bottle closer than usual (15 cm) for targeted application. Spray directly onto the hot spot and surrounding area.'),
            array('03', 'Allow to absorb', 'Let the aloe and allantoin absorb for 2&ndash;3 minutes before allowing your dog to move freely. The formula dries clear.'),
            array('04', 'Apply twice daily', 'For active hot spots, apply morning and evening. Continue for 3&ndash;5 days after visible improvement to prevent recurrence.'),
        ),
        'pro_tip' => array('&#x1FA79;', 'If the hot spot is weeping or has broken skin, consult your vet before applying. This product is designed for intact but irritated skin, not open wounds.'),
        'dogs' => array(
            'Dogs with active hot spots',
            'Compulsive lickers or chewers',
            'Allergy-triggered skin irritation',
            'Dogs that chew at bandaged areas',
            'Post-grooming skin sensitivity',
            'Breeds prone to hot spots (Retrievers, Shepherds)',
        ),
        'dog_cta_title' => 'Tired of the chew-then-treat cycle?',
        'dog_cta_desc'  => 'Most hot spot products just treat. Most deterrents just deter. This does both &mdash; simultaneously. Break the cycle with one formula.',
        'dog_cta_tags'  => array('Dual-Action', 'Soothing', 'Hot Spot Treatment', 'Vet-Safe'),
        'reviews_title'  => 'Soothed. Protected. Relieved.',
        'review_list' => array(
            array('David K.', 'Golden Retriever', 'My Golden gets hot spots every summer. This spray calmed the irritation AND stopped him from making it worse. First product that actually addresses both problems.'),
            array('Lisa P.', 'German Shepherd', 'After surgery, my Shepherd kept licking his stitches. The 2-in-1 soothed the area and the bitter taste stopped the licking. Exactly what we needed.'),
            array('Mark J.', 'Bulldog', 'Bulldogs and skin issues &mdash; it\'s constant. This has become our go-to for any red, irritated patch. Soothes first, deters second. Brilliant formula.'),
        ),
        'cta_title' => 'Soothe and protect. One spray.',
        'cta_sub'   => 'The dual-action formula for dogs that chew at sore areas.',
        'trust' => array(
            'Free shipping &pound;35+',
            '30-day guarantee',
            'Dual-Action',
            'Vet-Safe',
        ),
    ),

    // ─── SENSITIVE ───────────────────────────────────────────────
    'sensitive' => array(
        'id'            => 'sensitive',
        'name'          => 'Sensitive',
        'subtitle'      => 'Fragrance-Free Dog Shampoo &middot; 16 fl oz &middot; pH 6.2&ndash;7.0',
        'tagline'       => 'Some dogs need less, not more &mdash; and a shampoo that actually means it.',
        'desc'          => 'A genuinely fragrance-free, sulfate-free formula built around colloidal oatmeal, skin-identical Sodium PCA, and a soothing botanical stack that earns every ingredient on the label.',
        'price'         => '18.99',
        'currency'      => '$',
        'size'          => '16 fl oz',
        'badge'         => 'Fragrance-Free &middot; Sensitive Care',
        'type'          => 'Sensitive Dog Shampoo',
        'rating'        => '4.9',
        'reviews'       => '186',
        'bottle_badge'  => 'Fragrance-Free',
        'bottle_ings'   => array(
            array('Colloidal Oatmeal', '1.5%'),
            array('Sodium PCA', '0.3%'),
            array('Aloe Vera', '1.0%'),
            array('Panthenol', '0.5%'),
        ),
        'stats' => array(
            array('18', 'Ingredients'),
            array('0%', 'Fragrance'),
            array('6.2&ndash;7.0', 'Target pH'),
            array('0%', 'Sulfates'),
            array('MIT-Free', 'Preservative System'),
        ),
        'benefits_title' => 'Four reasons dogs with sensitive skin trust this formula.',
        'benefits' => array(
            array('&#x1F33E;', 'FDA-Recognised Oat Active', 'Colloidal oatmeal at 1.5% is an FDA-recognised skin protectant. It soothes irritation, reduces transepidermal water loss, and deposits a protective film on the skin.'),
            array('&#x1F4A7;', 'Skin-Identical Sodium PCA', 'Your dog\'s skin naturally produces Sodium PCA as part of its Natural Moisturizing Factor. Adding it back restores what sensitive skin loses. Rare in pet care.'),
            array('&#x1F33F;', 'Amino Acid Surfactant System', 'Three plant-derived cleansers &mdash; Decyl Glucoside, Cocamidopropyl Betaine, and Sodium Lauroyl Sarcosinate &mdash; gentle enough for daily use, effective enough to actually clean.'),
            array('&#x1F33C;', 'Four-Layer Soothing Complex', 'Panthenol, Allantoin, Aloe Vera, and Chamomile each address irritation through a different mechanism. The most comprehensive soothing stack in any rinse-off pet shampoo.'),
        ),
        'ingredients' => array(
            array('&#x1F33E;', 'Colloidal Oatmeal', '1.5%', 'Avena Sativa Kernel Flour. FDA-recognised skin protectant. Reduces itch, strengthens barrier function, and deposits a soothing film.', true, 'HERO'),
            array('&#x1F4A7;', 'Sodium PCA', '0.3%', 'Skin-identical Natural Moisturizing Factor component. Restores what sensitive skin loses &mdash; genuine barrier restoration.', true, 'HERO'),
            array('&#x1F33F;', 'Aloe Vera', '1.0%', 'Aloe Barbadensis Leaf Juice. Soothes, cools, and hydrates irritated skin immediately on contact.', true, 'DIFFERENTIATOR'),
            array('&#x1F9EC;', 'Panthenol (B5)', '0.5%', 'Pro-Vitamin B5. Penetrates the hair shaft to lock in moisture, improve coat elasticity, and build shine.', false, ''),
            array('&#x1F33C;', 'Allantoin + Chamomile', '0.3% + 0.2%', 'Allantoin promotes skin cell turnover. Chamomile adds a fourth soothing pathway. The most complete botanical pairing in this category.', false, ''),
            array('&#x1F6E1;&#xFE0F;', 'EWG-Listed Preservative', '1.0%', 'Phenoxyethanol (0.8%) + Ethylhexylglycerin (0.2%). MIT-free. Paraben-free. EWG-listed.', false, ''),
        ),
        'inci' => 'Water, Glycerin, Decyl Glucoside, Cocamidopropyl Betaine, Sodium Lauroyl Sarcosinate, Avena Sativa (Oat) Kernel Flour, Aloe Barbadensis Leaf Juice, Panthenol, Hydrolyzed Oat Protein, Sodium PCA, Allantoin, Guar Hydroxypropyltrimonium Chloride, Chamomilla Recutita (Chamomile) Flower Extract, Tocopheryl Acetate, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Sodium Chloride',
        'steps' => array(
            array('01', 'Wet thoroughly', 'Saturate your dog\'s coat completely with lukewarm water. Thorough wetting helps the formula distribute evenly.'),
            array('02', 'Apply gently', 'Dispense into your hands first, then work through the coat in sections. The low-foam lather is intentional.'),
            array('03', 'Leave on 2&ndash;3 min', 'Allow oatmeal, allantoin, and aloe to work. The soothing happens during the dwell time.'),
            array('04', 'Rinse completely', 'Rinse until water runs clear. Residual shampoo is the most common cause of post-bath irritation.'),
        ),
        'pro_tip' => array('&#x1F33E;', 'For dogs with atopic dermatitis, consistent weekly bathing with this formula progressively calms the itch cycle. Consistency matters more than frequency.'),
        'dogs' => array(
            'Dogs with atopic dermatitis or chronic itch',
            'Allergy-prone dogs &mdash; seasonal or environmental',
            'Puppies (8 weeks and older)',
            'Senior dogs with thinning or dry coat',
            'Post-surgery or post-treatment recovery',
            'Rescue dogs with unknown skin history',
            'Multi-dog households wanting one reliable shampoo',
        ),
        'dog_cta_title' => 'One bottle for every dog in the house.',
        'dog_cta_desc'  => 'Formulated to be safe for puppies, senior dogs, post-surgery recovery, and dogs with atopic dermatitis. Vet-trusted actives. Fragrance-free. pH balanced.',
        'dog_cta_tags'  => array('Fragrance-Free', 'Vet-Trusted Actives', 'pH 6.2&ndash;7.0', 'All Breeds'),
        'reviews_title'  => 'Sensitive skin. Satisfied owners.',
        'review_list' => array(
            array('Maya K.', 'French Bulldog', 'My Frenchie has had skin issues since she was a puppy. Three weeks with this shampoo and I\'m genuinely shocked. No redness after baths. The zero-fragrance claim is real.'),
            array('Dr. Sarah P.', 'Vet Nurse, 12 years', 'As a vet nurse I recommend this to clients whose dogs have post-bath flares. The oatmeal-Panthenol combination is exactly what reactive skin needs.'),
            array('Rachel M.', 'Foster Carer &middot; 60+ dogs', 'I foster dogs for a local rescue. Every dog that comes through my house gets bathed in this now. Clean label, honest formula, nothing hidden.'),
        ),
        'cta_title' => 'The nothing-extra shampoo.',
        'cta_sub'   => 'For the dog who needs exactly that.',
        'trust' => array(
            'Free shipping $35+',
            '30-day guarantee',
            'Fragrance-Free',
            'Sulfate-Free',
        ),
    ),

    // ─── ITCH RELIEF ─────────────────────────────────────────────
    'itch-relief' => array(
        'id'            => 'itchrelief',
        'name'          => 'Itch Relief',
        'subtitle'      => 'Salicylic Acid &amp; Niacinamide &middot; 16 fl oz &middot; pH 5.5&ndash;6.5',
        'tagline'       => 'The dermatologist combination your dog\'s skin has been waiting for.',
        'desc'          => 'Salicylic acid and niacinamide &mdash; the actives your vet knows &mdash; in a formula built for daily life. Surrounded by Pomegranate, Kiwi, Yucca, and Papaya. Intentionally tea tree-free. Fully transparent.',
        'price'         => '23.99',
        'currency'      => '$',
        'size'          => '16 fl oz',
        'badge'         => 'Vet-Grade Actives &middot; Itch Relief',
        'type'          => 'Itch Relief Dog Shampoo',
        'rating'        => '4.8',
        'reviews'       => '243',
        'bottle_badge'  => 'Tea Tree-Free',
        'bottle_ings'   => array(
            array('Salicylic Acid', '0.4%'),
            array('Niacinamide', '0.5%'),
            array('Colloidal Oatmeal', '1.5%'),
            array('4-Botanical Blend', '0.5%'),
        ),
        'stats' => array(
            array('23', 'Ingredients'),
            array('0.4%', 'Salicylic Acid'),
            array('0.5%', 'Niacinamide'),
            array('5.5&ndash;6.5', 'Target pH'),
            array('0%', 'Tea Tree Oil'),
            array('4', 'Named Botanicals'),
        ),
        'benefits_title' => 'Vet-grade actives meets botanical intelligence.',
        'benefits' => array(
            array('&#x1F9EA;', 'Salicylic Acid + Niacinamide', 'The BHA trusted in human dermatology for decades, paired with the most-recognised anti-inflammatory active in modern skincare. Now in your dog\'s shampoo.'),
            array('&#x1F33A;', '4-Botanical Superstrand', 'Pomegranate, Kiwi, Yucca, and Papaya &mdash; all four listed individually by INCI name. We don\'t hide behind &ldquo;botanical complex.&rdquo;'),
            array('&#x1F6AB;', 'Intentionally Tea Tree-Free', 'Tea tree oil is a documented toxicity concern in dogs. We researched it. We found better alternatives. We left it out.'),
            array('&#x1F33E;', 'Oatmeal + Sodium PCA Base', 'The same colloidal oatmeal and Sodium PCA base as our Sensitive SKU. The itch relief stack doesn\'t sacrifice gentleness for efficacy.'),
        ),
        'ingredients' => array(
            array('&#x1F9EA;', 'Salicylic Acid', '0.4%', 'BHA. Addresses flaky buildup that drives the itch-scratch cycle. Disrupts the keratin layer trapping allergens against skin.', true, 'HERO ACTIVE'),
            array('&#x2728;', 'Niacinamide', '0.5%', 'Anti-inflammatory, barrier-repairing, sebum-regulating. One of the only dog shampoos that includes it.', true, 'DIFFERENTIATOR'),
            array('&#x1F33E;', 'Colloidal Oatmeal', '1.5%', 'FDA-recognised skin protectant. Ensures the formula soothes as effectively as it treats.', true, 'SOOTHING BASE'),
            array('&#x1F33A;', 'Pomegranate', '0.5% blend', 'Punica Granatum. Antioxidant-dense polyphenol extract. Protects skin from oxidative stress.', false, ''),
            array('&#x1F95D;', 'Kiwi + Yucca + Papaya', '0.5% blend', 'Brightening enzymes, natural saponins, and proteolytic activity. All three listed by INCI individually.', false, ''),
            array('&#x1F4A7;', 'Butylene Glycol', '1.0%', 'Upgraded from propylene glycol. Dissolves Salicylic Acid for stable dispersion. Cleaner consumer perception.', false, ''),
        ),
        'inci' => 'Water, Glycerin, Decyl Glucoside, Cocamidopropyl Betaine, Sodium Lauroyl Sarcosinate, Avena Sativa (Oat) Kernel Flour, Aloe Barbadensis Leaf Juice, Butylene Glycol, Niacinamide, Panthenol, Hydrolyzed Oat Protein, Punica Granatum (Pomegranate) Extract, Actinidia Chinensis (Kiwi) Extract, Yucca Schidigera Extract, Carica Papaya Fruit Extract, Salicylic Acid, Sodium PCA, Allantoin, Guar Hydroxypropyltrimonium Chloride, Chamomilla Recutita (Chamomile) Flower Extract, Tocopheryl Acetate, Phenoxyethanol, Ethylhexylglycerin, Fragrance, Citric Acid, Sodium Chloride',
        'steps' => array(
            array('01', 'Wet thoroughly', 'Saturate coat with lukewarm water. For active hot spots, use slightly cooler water to avoid aggravating inflammation.'),
            array('02', 'Target problem areas', 'Apply directly to the most affected areas &mdash; paws, belly, flanks, base of tail &mdash; before working through the full coat.'),
            array('03', 'Leave on 5 minutes', 'For Salicylic Acid and Niacinamide to work effectively, allow 5 minutes minimum dwell time.'),
            array('04', 'Rinse, repeat weekly', 'Rinse completely. For seasonal allergies or persistent itch, weekly bathing progressively breaks the itch cycle.'),
        ),
        'pro_tip' => array('&#x1F9EA;', 'Salicylic Acid works best at a slightly acidic pH &mdash; which is why this formula is pH 5.5&ndash;6.5 rather than 6.2&ndash;7.0. The lower pH keeps the SA in its most efficacious form.'),
        'dogs' => array(
            'Dogs with seasonal or environmental allergies',
            'Persistent scratching licking paws or rubbing face',
            'Flaky skin dandruff or scaly patches',
            'Hot spot-prone or recurring skin irritation',
            'Dogs who\'ve exhausted basic sensitive shampoos',
            'Owners wanting actives without a prescription',
            'Ingredient-literate pet parents who read the label',
        ),
        'dog_cta_title' => 'Between the $10 shampoo and the $80 vet visit.',
        'dog_cta_desc'  => 'This formula is the credible third option &mdash; clinically-informed actives, full ingredient transparency, accessible price, no prescription required.',
        'dog_cta_tags'  => array('Salicylic Acid', 'Niacinamide', 'Tea Tree-Free', 'pH 5.5&ndash;6.5', 'Transparent INCI'),
        'reviews_title'  => 'Itch stopped. Owners convinced.',
        'review_list' => array(
            array('James T.', 'Golden Retriever', 'My Golden has seasonal allergies every spring. The salicylic acid is doing exactly what it promises &mdash; the flaking is gone and the scratching has dropped significantly.'),
            array('Priya S.', 'Dalmatian', 'The tea tree-free claim made me buy it first. My previous vet said avoid tea tree on dogs. My Dalmatian\'s hot spots have been calmer for the past month.'),
            array('Dr. Lin C.', 'Holistic Veterinarian', 'This is the first commercial dog shampoo I\'ve felt confident recommending without caveats. The pomegranate-papaya combination for enzymatic exfoliation is genuinely clever.'),
        ),
        'cta_title' => 'Clinically-minded. Botanically driven.',
        'cta_sub'   => 'Built for the itch.',
        'trust' => array(
            'Free shipping $35+',
            '30-day guarantee',
            'Tea Tree-Free',
            'Transparent INCI',
        ),
    ),
);
